### ISSUE TITLE
Project Team Timeline

### ISSUE THREAD

**Issue by katstine** [ucsdlib/uc-linked-data#12]
I started roughing out a [timeline](https://docs.google.com/spreadsheets/d/1unDJh7tCHX42EVfhYg_xmV5B3Fu6v9WFjocnAf8Efgc/edit?usp=sharing) for us, using the tasks and deliverables described in the project charge. Timeframes for each task (as well as task-task sequencing) are all guesses, and subject to change given the iterative nature of the work we have ahead. :)

**Comment by arwenhutt** [comment]
This looks really good @katstine!  Thank you so much for putting this together :)
