### ISSUE TITLE
Strategic priorities identification and alignment

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#14]
Identify UC Strategic priorities that may align with LD possibilities

@cstahmer  will share the COUL priorities doc

**Comment by cstahmer** [comment]
Here are the CUL strategic priorities that we talked about last time. The idea was that we try, as much as possible, to point out where our recommendations align with these:

[http://libraries.universityofcalifornia.edu/about/vision-and-priorities](http://libraries.universityofcalifornia.edu/about/vision-and-priorities)

**Comment by ngeraci** [comment]
In progress: https://github.com/ucsdlib/uc-linked-data/wiki/Linked-data-and-UC-Libraries-strategic-priorities
