### ISSUE TITLE
Framework for report

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#19]
set up framework, outline for report (document, table of contents, etc.)

**Comment by cstahmer** [comment]
Not sure where to put this, so I'm putting here.  Here are the CUL strategic priorities that we talked about last time.  The idea was that we try, as much as possible, to point out where our recommendations align with these:

[http://libraries.universityofcalifornia.edu/about/vision-and-priorities](http://libraries.universityofcalifornia.edu/about/vision-and-priorities)

**Comment by rmjaffe** [comment]
I can do this.

**Comment by arwenhutt** [comment]
Draft outline/strawman for the report structure for discussion https://docs.google.com/document/d/13rotneLJmE1k6OKiSX6oofjlVzIG5qNIyl3MGEMlm7k/edit#
