### ISSUE TITLE
Initial outline for webinars

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#20]
possible topics, structure, etc.

**Comment by chrissyrissmeyer** [comment]
Chrissy still has webinar privileges on her UCSB Zoom account, and it happy to host if needed. 

We hosted Samvera Virtual Connect in 2017, and for that put together a variety of instructions:
- Host schedule/instructions: https://docs.google.com/document/d/1OhBCL0cYCDxt2F-Yr-r5hnPBDcGkQ9LyFz_eC-IJ3ls/edit
- Detailed presenter instructions (we have three different types for SVC): https://drive.google.com/drive/folders/0BxNsbR6fxrHHaDlMMzB1OXVybTg
- Another Zoom planning document (includes example messages, etc.): https://docs.google.com/document/d/1S8WeY0oHXNX66LRaTVPITEBOXD1yncGzzGkoDgPBPIE/edit

(This might all be overkill for a UC wide event, but hopefully it is helpful!)

**Comment by arwenhutt** [comment]
While trying to compose an email about the webinars, I decided to first try taking a stab at integrating all of the different, and great, ideas together!  

Here's a draft: https://docs.google.com/document/d/17X98lkCN6DZTH03e-NNc-k35BnUwjXcpZHcBIB0eyYo/edit?usp=sharing 

Feedback needed!

**Comment by rmjaffe** [comment]
@arwenhutt Thank you so much for doing this.  I really like this outline, especially how you've it up so that the webinars build on one another.

**Comment by arwenhutt** [comment]
Thanks @rmjaffe!

**Comment by arwenhutt** [comment]
Just noting that this will need to be revised based on feedback from DOC.
