### ISSUE TITLE
Update UC-DLFx sched

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/uc-linked-data#21]
Currently, because I submitted the proposal, I am listed as the only person facilitating our Birds of a Feather lunch. I am happy to contact the organizers and request an update if I can get a list of those who plan to be there.

Can everyone take a moment and comment below to let me know if they will be attending the session? (I suspect that all of us attending will be help facilitate in one way or another, even if we aren't all speaking.) Once I hear back from everyone, I will contact the organizers requesting the update.

Thank you!

**Comment by chrissyrissmeyer** [comment]
I'll be there!

**Comment by kbalster** [comment]
I will not be attending.

**Comment by arwenhutt** [comment]
I'll be there

**Comment by rmjaffe** [comment]
I'll be there too.

**Comment by cstahmer** [comment]
I'll be there

**Comment by chrissyrissmeyer** [comment]
Haiquing confirmed via email that he will not be attending UC-DLFx.

**Comment by chrissyrissmeyer** [comment]
@katstine and @ngeraci: do either of you know if you will be able to attend the session? Was hoping to request the update this week.

**Comment by katstine** [comment]
Hi Chrissy,

I’ll be at UCDLFx, but unfortunately at another BoF that is running concurrent to the Linked Data BoF. I’m happy to help with planning, though!

Kathryn

**Comment by ngeraci** [comment]
I'll be there at the session! Also, since I'm on the local arrangements committee, I have admin access to Sched and can just go in and make the update.

**Comment by chrissyrissmeyer** [comment]
@ngeraci: Awesome! Looks like it will be the following attending:

- Arwen Hutt
- Noah Geraci
- Rachel Jaffe
- Carl Stahmer
- Chrissy Rissmeyer

(No Kathryn, Haiqing, or Kevin). Could you please update the Sched?

**Comment by chrissyrissmeyer** [comment]
@ngeraci: Nevermind, I see you did it already. Thank you!
