### ISSUE TITLE
Webinar content area - report highlights/themes/etc.

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#32]
Notes:
* 

Possible audience focus:
* 

Link to google doc https://docs.google.com/document/d/17X98lkCN6DZTH03e-NNc-k35BnUwjXcpZHcBIB0eyYo/edit?usp=sharing

**Comment by arwenhutt** [comment]
Did not discuss this section at the 5/18 meeting

**Comment by arwenhutt** [comment]
Link to template ticket https://github.com/ucsdlib/uc-linked-data/issues/37

**Comment by cstahmer** [comment]
Nobody else has signed up for this ticket yet, so I wen't ahead and assigned it to myself.  If someone else had their heart set on it, just let me know and I'll happily apply work somewhere else where I can be of use.  I'll start working on content after the weekend.
