### ISSUE TITLE
Webinar content area - use cases

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#33]
Notes:
* use projects to illustrate when possible (UC, then external lib, then non-lib)

Possible audience focus:
* public service / managers

Link to google doc https://docs.google.com/document/d/17X98lkCN6DZTH03e-NNc-k35BnUwjXcpZHcBIB0eyYo/edit?usp=sharing

**Comment by arwenhutt** [comment]
Link to template ticket https://github.com/ucsdlib/uc-linked-data/issues/37

**Comment by katstine** [comment]
I'm happy to help with this one.
