### ISSUE TITLE
Webinar content area - linked data essentials

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#34]
Possible audience focus:
* non-technial/new to linked data

Link to google doc https://docs.google.com/document/d/17X98lkCN6DZTH03e-NNc-k35BnUwjXcpZHcBIB0eyYo/edit?usp=sharing

**Comment by arwenhutt** [comment]
Link to template ticket https://github.com/ucsdlib/uc-linked-data/issues/37

**Comment by ngeraci** [comment]
starting work here: https://docs.google.com/presentation/d/1Dvl51RMp1W-yUA_LV0NYXoX2ndRsQeKLRB6Q3kjNL5s/edit#slide=id.g3adbf8df9a_0_49
