### ISSUE TITLE
Webinar content area - opportunities for systemwide work

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#35]
Notes:
* what we can achieve together

Possible audience focus:
* manager

Link to google doc https://docs.google.com/document/d/17X98lkCN6DZTH03e-NNc-k35BnUwjXcpZHcBIB0eyYo/edit?usp=sharing

**Comment by rmjaffe** [comment]
Just a heads up, I am on vacation 5/23-6/5.  Unfortunately, I've had little to no time to spend with this, but I will pick it up once I return.

**Comment by arwenhutt** [comment]
Link to template ticket https://github.com/ucsdlib/uc-linked-data/issues/37
