### ISSUE TITLE
Webinar 2 - Current activity, UC and beyond

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#39]
Focused on projects/work at UC.  More discussion of technical and infrastructure side of the work than webinar 1.

Goals: 
1. Showcase UC linked data activity
2. Examples of current work

Audience: metadata, technical, managers

Presentation template description: #37
Related tickets: #20, #36

**Comment by katstine** [comment]
draft slide deck (as of early August): https://docs.google.com/presentation/d/1lUBnVKOLcutdXU5pBsDGX8ur1ZbXwTjnP3mquns7aY8/edit#slide=id.g3add4720cc_0_0
