### ISSUE TITLE
UC DLF - proposal

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#4]
Finalize proposal for UC DLF session.  

Please edit freely: 
https://docs.google.com/a/ucsd.edu/document/d/1xxmLqnVPT-cjEIfumDX8LZn1Jn_U0_L7gIZXEwzaD8M/edit?usp=sharing

**Comment by chrissyrissmeyer** [comment]
I submitted this today during the Programming Committee meeting.
