### ISSUE TITLE
Request Zoom webinar license

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/uc-linked-data#41]
In order to host a Zoom webinar, you need to request from campus IT that a special webinar license be applied to your account.

**Comment by chrissyrissmeyer** [comment]
I submitted a ticket with UCSB's ETSC this afternoon: [RITM0028176](https://ucsb.service-now.com/ess_portal/main_content.do?sysparm_content_url=sc_req_item.do?sys_id=873f4f8edb3cab00b9fbfbd61d96191d)

I'll update the group once I hear back from them.

**Comment by arwenhutt** [comment]
If @chrissyrissmeyer is out, then she'll have a backup at UCSB to start the webinar and then transfer the host to @kbalster - who will be back up host.  @arwenhutt can be back up back up

**Comment by arwenhutt** [comment]
@chrissyrissmeyer will the dates for the license request need to be modified?

**Comment by chrissyrissmeyer** [comment]
@arwenhutt I don't believe so. The last time I had a license, I had it on my account for over 1 year (and campus IT asked if I had anything scheduled before removing it from my account). 

Closing this ticket since I was able to confirm this morning that the webinar license has been added back to my account.
