### ISSUE TITLE
Identify additional examples

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#63]
that would be necessary or just nice to have, create tickets for them

**Comment by arwenhutt** [comment]
From 11/23 & 11/30 meetings, we talked about adding more examples of current uses including "linked data you didn't know you were using"

**Comment by arwenhutt** [comment]
https://www.wikidata.org/wiki/Wikidata:Tools

**Comment by cstahmer** [comment]
http://www.geonames.org/  is LD based

**Comment by cstahmer** [comment]
http://www.nines.org/

**Comment by cstahmer** [comment]
Google Knowledge Cards

**Comment by cstahmer** [comment]
Not really a "you didn't know you were using" example, but I always like to show a Relfinder example, built of dbpedia.

**Comment by cstahmer** [comment]
https://www.data.gov/
