### ISSUE TITLE
webinar email distribution

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#65]
Identify where email announcements will be sent and by whom: 
- group members will distribute within their organization
- Irvine ? 
- San Francisco ?
- CKGs ?
- Other ?

**Comment by arwenhutt** [comment]
@arwenhutt @chrissyrissmeyer @ngeraci try identify contacts in Metadata at Irvine and UCSF

CKGs:
* Digital Repositories
* Cataloging & Metadata
* Preservation

@katstine will ask about SILS distribution

**Comment by chrissyrissmeyer** [comment]
UCSF: I'd send to Charlie Macquarie and also Susan Boone (Technical Services Operations Manager).

As a general thought, it might not be a bad idea to send directly to everyone who responded to the original survey.

**Comment by arwenhutt** [comment]
https://docs.google.com/document/d/1knJ2-KoMoO8oui1DF6hHOuMgfMlNVXNLJSvESjFzVT8/edit

**Comment by arwenhutt** [comment]
The announcement is ready to be distributed, though I think it would be better to wait until Monday! I'll be sending it to you all formatted as an email for convenience.

Everyone has been assigned this ticket.  Please comment when you've sent it to your org/groups, and remove your name.

@arwenhutt - survey respondents, UCI, UCSF, SILS contact, DOC, UCSD, digital repository md ckg, indirectly to research curation ckg
@chrissyrissmeyer - UCSB, Preservation ckg
@kbalster - UCLA, CM CKG
@katstine - CDL, indirectly to Shared Visual Resources CKG
@ngeraci - UCR
@cstahmer - UCD
@rmjaffe - UCSC
@hlinUCB - Berkeley

**Comment by arwenhutt** [comment]
~survey respondents, UCI, UCSF, SILS contact, DOC, UCSD, digital repository md ckg, indirectly to research curation ckg~ - done!

**Comment by arwenhutt** [comment]
FYI - I also added the announcement to the wiki https://github.com/ucsdlib/uc-linked-data/wiki/Linked-Data-Project-Team-Webinars

**Comment by rmjaffe** [comment]
Sent to UCSC!

**Comment by chrissyrissmeyer** [comment]
Sent to UCSB and the preservation CKG

**Comment by kbalster** [comment]
Sent to UCLA and CMCKG

**Comment by ngeraci** [comment]
sent to UCR

**Comment by arwenhutt** [comment]
verified announcement was sent to data curation ckg
