### ISSUE TITLE
Linked data for maintenance of authority headings and controlled vocabulary

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/uc-linked-data#7]
The labels for controlled terms expressed as URIs can be updated on a regular basis by updating a cache without requiring additional maintenance by cataloging/metadata staff (or external vendors). Many of the controlled vocabularies we use are constantly changing, common examples include the monthly [updates to LCSH](https://www.loc.gov/aba/cataloging/subject/weeklylists/) and changes to name headings in NAF (i.e., adding death dates). In the past, these types of updates for our MARC records were often performed by catalog maintenance staff or external authority maintenance vendors (now some ILS vendors handle this piece). But this kind of systematic maintenance has often not been performed consistently or at all in our digital library systems. 

This “behind the scenes” functionality doesn’t have much of a visible presence, but could be a powerful and immediate benefit for staff from the use of linked data. 

Example:
http://alexandria.ucsb.edu/lib/ark:/48907/f31z42qh (object view incorporating labels)
http://alexandria.ucsb.edu/lib/ark:/48907/f31z42qh.ttl (turtle file with URIs)

**Comment by chrissyrissmeyer** [comment]
Adapted from old UCSB/UCSD created document: https://docs.google.com/document/d/1IF80HofbWh7iK5Oxh5vfFSmHs7MEw49rr4t0LebNWOA/edit?usp=sharing

**Comment by rmjaffe** [comment]
UCSC is also exploring this in the space of our Hyrax implementation project.  I don't know if it would be presented as a second use-case or as an add-on to this one, but we are also looking at transforming our local controlled terms and brief authority records into linked data so that we can  automate the authority control work around those terms as well.

**Comment by cstahmer** [comment]
Label maintenance is one of the areas that we've focused on as an area of potential improved efficiency and performance.  In are current workflow, we have update/import an entire record if a change is going to be made to an authority literal (label).  With URI's, we _think_ we should be able to deliver and update labels to URIs on-the-fly through a centralized reconciliation service.  Testing this was part of OCLC's first name authority pilot, and we are working on some updated testing with them now.

**Comment by hlinUCB** [comment]
I would like to suggest to add this web site a resource. https://www.w3.org/2005/Incubator/lld/XGR-lld-vocabdataset-20111025/
