### ISSUE TITLE
Set (updated) date for Webinar 2

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#70]
We'll discuss as a group at the 10/26 meeting dependent on @katstine 's schedule.

**Comment by arwenhutt** [comment]
Tentative January 16th @12 (dependent on @cstahmer's schedule for Webinar 1)

**Comment by cstahmer** [comment]
Right now I'm out of the office the first week of January, but can do any time after that.

On Oct 26, 2018 1:12 PM, arwenhutt <notifications@github.com> wrote:

Tentative January 16th @12<https://github.com/12> (dependent on @cstahmer<https://github.com/cstahmer>'s schedule for Webinar 1)

**Comment by arwenhutt** [comment]
@cstahmer Great! How about January 9th?

**Comment by arwenhutt** [comment]
Webinar 2 = January 16th
