### ISSUE TITLE
roles for webinars

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#73]
From previous meeting:
- Speakers @cstahmer @katstine 
- Zoom host @chrissyrissmeyer (backup @kbalster)
    - muting, etc.
    - switch control to presenter
    - technical issues
- Official moderator @arwenhutt 
    - introduction
    - reads Q&A
- Chat monitor @kbalster (backup @ngeraci)
    - keeps an eye out for technical issues
    - questions from chat to "Q&A"

Link to @chrissyrissmeyer 's doc outlining roles https://docs.google.com/document/d/1uUmHWIPE_QyHAOVb1Qb6dPZ2otdsSvWWt2v188WXn9s/edit

**Comment by arwenhutt** [comment]
@chrissyrissmeyer okay, I think this is ready for Zoom setup

**Comment by chrissyrissmeyer** [comment]
I have added all of the folks with official roles as panelists for the webinars. If you don't have an official role you are taking on in the webinar (@rmjaffe and @hlinUCB), you'll need to register for the webinar as an attendee.
