### ISSUE TITLE
Slides for linked data syntax (rdf, etc.)

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#76]
This slide needs a brief description:
https://docs.google.com/presentation/d/1Dvl51RMp1W-yUA_LV0NYXoX2ndRsQeKLRB6Q3kjNL5s/edit?disco=AAAACcQgP_M

And the one right after it needs more content.  From conversation at 12/14 meeting this could be a very simple statement in each of the different serializations.

**Comment by arwenhutt** [comment]
@kbalster to take excerpts of @hlinUCB 's examples to fit on slide

**Comment by kbalster** [comment]
Excerpts added. Let me know if any changes are needed.

**Comment by arwenhutt** [comment]
@kbalster Looks great!  Thanks!
