### ISSUE TITLE
Supplement local data with external linked data

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/uc-linked-data#8]
Having a URI reference in a local record to an external linked data record allows the local system to make decisions about what supplemental data would be of value to bring in the context of the local system. For example, the object in the authority example reference the American Film Manufacturing Company (AFMC) as the creator and contributor of the content. This reference could include a triple (link) to the [DBPedia record](http://dbpedia.org/page/American_Film_Manufacturing_Company) for that same entity. One may then decide that it is of value to also show users more information about the AFMC such as the founders, other web links with additional information, other films by the company, etc. This information, in addition to being displayable to end users, could be used to enhance the search experience so that if someone searched for one of the founders in a completely different context, they might come across this additional information, potentially strengthening the research or browsing experience. Some potential ideas:

- For names, provide link for more information (e.g., wikipedia, ULAN, VIAF, FAST) in the user interface. Example: 
http://www.digibis.com/digimus_demo/en/agents/34.html
- For names, provide brief information (similar to abbreviated knowledge cards) in the user interface. Example: http://www.bbc.co.uk/music/artists/149f91ef-1287-46da-9a8e-87fee02f1471 
For names and topics, include alternate terms from external data sources to improve searching for the user.  
- For names and topics, use related terms from external data sources to provide users with improved suggestions for failed searches.
- For topics, use narrower terms from external data sources to include more specific terms in a user's search.  E.g. if a user searches for “ball games”, narrower terms such as baseball, basketball could be included in search results.
- Use taxonomic relationships to create a browse interface which lets users navigate to broader or narrower concepts. E.g. if a user searches on baseball, they could browse up to the broader category of “ball games” and then down to other narrower terms.  
     * Example of browsing using taxonomic relationships for material: http://www.digibis.com/digimus_demo/en/schemas/2.html
     * This interface shows this kind of browse but is NOT using Linked Data so it is static and so will not reflect changes made to the structure of the vocabulary over the years. This was a search for “trees” which can then be refined by more specific types of trees included into this collection. https://webapp1.dlib.indiana.edu/cushman/results/result.do?query=subject:%22Trees%22
- For related entities (e.g., library or library department), enhancing user interface by pulling in location and contact information. Example: http://www.digibis.com/digimus_demo/en/musobjects/2.html
- For geographic locations, use information from an external source to show average temperature, map of location, etc. Example: https://www.asist.org/wp-content/uploads/2016/12/Godby-Figure-1.jpg

**Comment by chrissyrissmeyer** [comment]
From old UCSB/UCSD created document: https://docs.google.com/document/d/1IF80HofbWh7iK5Oxh5vfFSmHs7MEw49rr4t0LebNWOA/edit?usp=sharing

**Comment by chrissyrissmeyer** [comment]
Adding some other examples from the above document.

> Examples:
> There's some interesting demonstration data here:
> I believe it is using Linked Data vocabularies provided by the Getty, but shows a number of possibilities:
> Enhancing a name record for users by pulling in external information, linking to other sources (ulan, viaf, wikipedia, fast): http://www.digibis.com/digimus_demo/en/agents/34.html
> Enhancing an object record, I believe pulling in a map, contact info and an external link for related agents (in this case the museum): http://www.digibis.com/digimus_demo/en/musobjects/2.html
> They also seem to be using the taxonomic tree for materials (http://www.digibis.com/digimus_demo/en/schemas/2.html) and processes and techniques (http://www.digibis.com/digimus_demo/en/schemas/28.html), though I think this still needs some UI work (it get's weedy, really quickly) and would look a lot better with a larger body of data.
>  
> BBC music is pulling in bio's from Wikipedia http://www.bbc.co.uk/music
> http://www.bbc.co.uk/music/artists/149f91ef-1287-46da-9a8e-87fee02f1471 
> 
> And it sounds like a lot more throughout the BBC: http://www.bbc.co.uk/academy/technology/software-engineering/semantic-web
> http://www.bbc.co.uk/ontologies

**Comment by chrissyrissmeyer** [comment]
Also wondering if this should be split into multiple use cases.

**Comment by kbalster** [comment]
On the MARC bibliographic side of things, two possibilities quickly come to mind: 

1. Supplementing bibliographic descriptions with ONIX metadata - such as 505 contents notes.
2. Establishing URIs for individual serial issues which could allow for collaborative maintenance of issue identification between Library "check-in" staff, Abstract & Indexing services, and publishers. This one came up in the CONSER CSR to BIBFRAME Mapping Task Group final report: http://www.loc.gov/aba/pcc/bibframe/TaskGroups/CSR-PDF/FinalReportCONSERToPCCBIBFRAMETaskGroup.pdf
