### ISSUE TITLE
Data Visualization

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/uc-linked-data#9]
Linked data can also be used to create interfaces for users to explore visual relationships between objects and data. 

* Linked Jazz: https://linkedjazz.org/network/
* UCI Artist Books: http://www.lib.uci.edu/sites/all/plodab/index.php

**Comment by chrissyrissmeyer** [comment]
From old UCSB/UCSD created document: https://docs.google.com/document/d/1IF80HofbWh7iK5Oxh5vfFSmHs7MEw49rr4t0LebNWOA/edit?usp=sharing

**Comment by cstahmer** [comment]
There's an interesting project at Texas A&M that aims to provide a visual/network based browsing experience of combined library and peer reviewed web published data.  Hits both the visualization and extending library data topics. http://bigdiva.org/
